### ISSUE TITLE
Multiple warnings when running sbt assembly with scalismo 0.91.0

### ISSUE THREAD

**Issue by Ghazi-Bouabene** [unibas-gravis/activator-scalismo-seed#10]
To reproduce:

* In the scalismo seed project, change the dependency to 0.91.0 (currently 0.90.0)
* Run a sbt assembly

Expected behavior: multiple such warning lines

...
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
...

This issue must be somehow related to the one reported here: 

https://github.com/sbt/sbt-assembly/issues/410#issuecomment-817073498

Any idea what could be causing this? (One thought was if the new native dependencies were compiled with sbt 1.4 that could've caused the issue .. however this is not the case since sbt 1.6.1 was used).

**Comment by marcelluethi** [comment]
Hi Ghazi

I also encountered that problem in other projects. I chose to ignore it, as it is only a warning and the resulting jar that was produced worked perfectly. Does it cause more problems for you than just these warning messages?

**Comment by Ghazi-Bouabene** [comment]
Hi Marcel,

Thanks a lot for your reply.  

The jar's functionality is indeed not affected. However, when the code and build process undergo quality assurance checks (e.g. static code analysis, ..) such warnings are not desired.

I would gladly implement a fix if possible, just have currently no clue what is causing this. Any idea what changed between 0.90 and 0.91 that could trigger this?

**Comment by marcelluethi** [comment]
According to [this article](https://eed3si9n.com/sbt-assembly-1.0.0) it has to do with a change in sbt. 
You could check if updating to the latest sbt and assembly version fixes it.

**Comment by Ghazi-Bouabene** [comment]
Used sbt version was already 1.6.2, however with assembly 0.14.10. Changing to sbt-assembly 1.1.0 does indeed solve the problem. Funny that this triggers with 0.91 and not 0.90. Anyhow, closing this. Thanks a lot for your help.
