### ISSUE TITLE
The problem showed in IntelliJ : Could not read stl mesh (received error code 20002..

### ISSUE THREAD

**Issue by herfrain** [unibas-gravis/activator-scalismo-seed#7]
scalismo.initialize()

// read a mesh from file, In this part,  the error appeared
val mesh = MeshIO.readMesh(new File("data/facemesh.stl")).get

**Comment by herfrain** [comment]
but in terminal, use "sbt run" , it is successful

**Comment by herfrain** [comment]
oh,i find it,the reason is the name of directory,it must be english

**Comment by Ghazi-Bouabene** [comment]
OK great, I will close the issue then.

**Comment by herfrain** [comment]
Thank you :)
